name: Create artifact
"on":
  workflow_dispatch: {}
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v2
        with:
          name: event.json
          path: ${{ github.event_path }}
