name: debug
on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/hello-world-js-action@v1.x
      - uses: gr2m/hello-world-js-action@v1.x
        with:
          greeting: Gregor
