name: debug
on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/collaborators/gr2m
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
