name: Debug
"on":
  workflow_dispatch: {}
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
    env:
      MATRIX: |
        [
          {
            "owner": "gr2m"
          },
          {
            "owner": "gr2m-sandbox",
            "repos": ["test"]
          }
        ]

  use-matrix:
    needs: [set-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ownersAndRepos: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      
    steps:
      - run: echo ${{ toJSON(matrix.ownersAndRepos) }}
    
