name: Debug
on:
  workflow_dispatch:
    inputs:
      foo:
        description: "When I say foo, you say bar! Foo"
        required: true
        default: "bar"
  push: {}
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # set MY_ENV environment variable
      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - run: echo "MY_ENV=${{ github.event.sender.login }}" >> $GITHUB_ENV
        if: github.event.sender.login
      - run: echo "MY_ENV=${{ github.event.inputs.foo }}" >> $GITHUB_ENV
        if: github.event.inputs.foo
      - run: 'echo "MY_ENV: $MY_ENV"'
