name: Debug
"on":
  workflow_dispatch: {}
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - if: '"1" > 0'
        run: echo "This should run."
      - if: '!("1" > 0)'
        run: echo "This should not run." && exit 1
