name: Debug
"on":
  workflow_dispatch: {}
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: ls
      - run: node --version
  two:
    runs-on: ubuntu-latest
    needs:
      - one
    steps:
      - run: ls
      - run: node --version
  three:
    runs-on: ubuntu-latest
    needs:
      - one
    steps:
      - run: ls
      - run: node --version
