name: Debug
"on":
  workflow_dispatch: {}
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: |
          {
            echo 'MULTI_LINE_JSON<<EOF'
            echo "matrix=$MATRIX"
            echo 'EOF'
          } >>"$GITHUB_OUTPUT"
    env:
      MATRIX: '[{"owner":"gr2m"},{"owner":"gr2m-sandbox","repos":["test"]}]'
      # [
      #   {
      #     "owner": "gr2m"
      #   },
      #   {
      #     "owner": "gr2m-sandbox",
      #     "repos": ["test"]
      #   }
      # ]

  use-matrix:
    needs: [set-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ownersAndRepos: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      
    steps:
      - run: echo ${{ toJSON(matrix.ownersAndRepos) }}
    
