name: Debug
"on":
  workflow_dispatch: {}
jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@main
        id: app-auth
        with:
          app-id: ${{ vars.GR2M_GITHUB_APP_ID }}
          private-key: ${{ secrets.GR2M_GITHUB_APP_PRIVATE_KEY }}
      - id: committer
        run: echo "string=${{steps.app-auth.outputs.app-slug}}[bot] <${{ steps.app-auth.outputs.installation-id }}+${{ steps.app-auth.outputs.app-slug }}[bot]@users.noreply.github.com>"  >> "$GITHUB_OUTPUT"
      - run: echo "committer string: ${{steps.committer.outputs.string}}"
