name: Debug
"on":
  repository_dispatch: {}
  workflow_dispatch: {}
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # this is not a real token don't you worry
      - run: echo ghp_eWcO7MRlWREC2rQjiEYH5FBiMUx2Tc2JxgZ3
