name: Debug
"on":
  workflow_dispatch: {}
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_file
        with:
          route: GET /repos/{repository}/contents/{path}
          repository: ${{ env.GITHUB_REPOSITORY }}
          path: .github/wip.yml
          mediaType: |
            format: raw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_file.outputs.data }}"
