name: Debug
"on":
  repository_dispatch: {}
  workflow_dispatch: {}
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # some comment here to test https://github.com/oscard0m/octoherd-script-update-action-version-in-workflows
      - uses: actions/checkout@v3
