# debugging https://github.com/gr2m/merge-schedule-action/issues/33

name: Schedule Debug
on:
  schedule:
    # https://crontab.guru/every-five-minutes
    - cron: */5 * * * *

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
