on:
  issues:
    types: [opened]

jobs:
  generate-text:
    runs-on: ubuntu-latest
    steps:
      - uses: vercel/ai-action@v2
        id: prompt
        with:
          model: "openai/gpt-5"
          api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
          prompt: |
            Is this an urgent issue? Say "yes" if it's preventing a user from doing something critical.

            Issue Title: ${{ github.event.issue.title }}

            Issue Body: ${{ github.event.issue.body }}
      - if: steps.prompt.outputs.text == 'yes'
        run: gh issue edit ${{ github.event.issue.number }} --add-label urgent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
