name: Test Schedule
on:
  schedule:
    - cron: "0 21 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: node -e 'console.log(JSON.stringify(require(process.env.GITHUB_EVENT_PATH), null, 2))'
